Program installed from the official Debian Testing repositories.

diff --git a/scripts/basics b/scripts/basics
--- a/scripts/basics
+++ b/scripts/basics
@@ -1,12 +1,9 @@
- #!/bin/bash
+#!/bin/bash
 
+set -e  # Exit immediately if a command exits with a non-zero status.
 set -x  # All executed commands are printed to the terminal
 
-gpg --recv-keys 445B9007
-gpg -a -o /tmp/bunkus.gpg --export 445B9007
-apt-key add /tmp/bunkus.gpg
-
-aptitude update ; aptitude install -y ca-certificates ; aptitude update ; aptitude install -y mkvtoolnix-gui
+aptitude update ; aptitude install -y mkvtoolnix-gui
 
 apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
 rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude
